apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-position-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-position-tracker
  template:
    metadata:
      labels:
        app: fleetman-position-tracker
    spec:
      containers:
      - name: fleetman-position-tracker
        image: supinfo4kube/position-tracker:1.0.1
        envFrom:
        - configMapRef:
          name: fleetman-config
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
  type: ClusterIP
  selector:
    app: fleetman-position-tracker
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP

