apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-queue
  template:
    metadata:
      labels:
        app: fleetman-queue
    spec:
      containers:
      - name: fleetman-queue
        image: supinfo4kube/queue:1.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8161
        - containerPort: 61616
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  type: ClusterIP
  selector:
    app: fleetman-queue
  ports:
  - port: 8161
    targetPort: 8161
    protocol: TCP
  - port: 61616
    targetPort: 61616
    protocol: TCP

