apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetman-webapp
  namespace: fleetman-001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fleetman-webapp
  template:
    metadata:
      labels:
        app: fleetman-webapp
    spec:
      containers:
      - name: fleetman-webapp
        image: supinfo4kube/web-app:1.0.0
#        resources:
#          limits:
#            memory: "128Mi"
#            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
  namespace: fleetman-001
spec:
  type: NodePort
  selector:
    app: fleetman-webapp
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http

