apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: fleetman-001
type: Opaque
data:
  password: bW9uZ29fcGFzcw== # Base64 encoded value of "mongo_pass"
  username: bW9uZ29fdXNlcg== # Base64 encoded value of "mongo_user"
