apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: fleetman-001
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard  # Must match the StorageClass name
  local:
    path: /mnt/mongo/data  # Path to the storage location on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker01  # Replace with the specific node name
