apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: fleetman-001
spec:
  resources:
    requests:
      storage: 500Mi
  #volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
